# Generated by Django 3.2.4 on 2021-07-09 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_uservote_mat_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uservote',
            name='mat_no',
            field=models.CharField(max_length=150),
        ),
    ]
